let Town = "Cambridge"
console.log("You Live in " +Town)
Town = "Manchester"
console.log("Stu Lives in " +Town)
Town = "London"
console.log("Yvonnne lives in " + Town)
console.log(Town.charAt(2))





let number1 = 15
let number2 = 20
let answer = number1 + number2
console.log(answer)
answer++
console.log(answer++)




town = "Paris"
console.log(`Bob lives in ${town} and is happy`)
console.log("Bob lives in " + town + " and is happy")
console.log('Bob lives in' + town )













